create table player_stats (
  id bigserial primary key,
  player_id text,
  player_display_name text,
  position text,
  season int,
  season_type text,
  team text,
  completions float,
  attempts float,
  passing_yards float,
  passing_tds float,
  passing_interceptions float,
  pacr float,
  carries float,
  rushing_yards float,
  rushing_tds float,
  rushing_fumbles float,
  receptions float,
  targets float,
  receiving_yards float,
  receiving_tds float,
  def_tackles_solo float,
  def_sacks float,
  def_interceptions float,
  def_pass_defended float,
  fg_made float,
  fg_att float,
  fg_pct float,
  punt_returns float,
  punt_return_yards float,
  kickoff_returns float,
  kickoff_return_yards float
);

create table team_stats (
  id bigserial primary key,
  team text,
  season int,
  season_type text,
  passing_yards float,
  passing_tds float,
  passing_interceptions float,
  rushing_yards float,
  rushing_tds float,
  receiving_yards float,
  receiving_tds float,
  def_tackles_solo float,
  def_sacks float,
  def_interceptions float,
  def_pass_defended float,
  fg_made float,
  fg_att float,
  fg_pct float
);

create table schedules (
  id bigserial primary key,
  game_id text,
  season int,
  game_type text,
  week int,
  away_team text,
  away_score float,
  home_team text,
  home_score float,
  result float,
  total float,
  overtime float,
  roof text,
  surface text,
  temp float,
  wind float
);

create table rosters (
  id bigserial primary key,
  season int,
  team text,
  position text,
  depth_chart_position text,
  jersey_number float,
  status text,
  full_name text,
  first_name text,
  last_name text,
  height float,
  weight float,
  college text,
  sleeper_id float,
  game_type text,
  years_exp float,
  entry_year float,
  rookie_year float,
  draft_club text,
  draft_number text
);

create table depth_charts (
  id bigserial primary key,
  season int,
  club_code text,
  week float,
  game_type text,
  full_name text,
  position text,
  depth_position text,
  team text,
  player_name text,
  pos_name text,
  pos_rank float
);

create table coaches (
  id bigserial primary key,
  season int,
  team text,
  head_coach text
);

create table team_seasons_wide (
  id bigserial primary key,
  team text not null,
  season int not null,
  qb_attempts float, qb_completions float, qb_passing_yards float,
  qb_passing_tds float, qb_interceptions float,
  qb_carries float, qb_rushing_yards float, qb_rushing_tds float,
  wr1_targets float, wr1_receptions float, wr1_receiving_yards float, wr1_receiving_tds float,
  wr2_targets float, wr2_receptions float, wr2_receiving_yards float, wr2_receiving_tds float,
  wr3_targets float, wr3_receptions float, wr3_receiving_yards float, wr3_receiving_tds float,
  rb1_carries float, rb1_rushing_yards float, rb1_rushing_tds float,
  rb1_targets float, rb1_receptions float, rb1_receiving_yards float, rb1_receiving_tds float,
  rb2_carries float, rb2_rushing_yards float, rb2_rushing_tds float,
  rb2_targets float, rb2_receptions float, rb2_receiving_yards float, rb2_receiving_tds float,
  te1_targets float, te1_receptions float, te1_receiving_yards float, te1_receiving_tds float,
  te2_targets float, te2_receptions float, te2_receiving_yards float, te2_receiving_tds float,
  team_passing_yards float, team_passing_tds float,
  team_rushing_yards float, team_rushing_tds float,
  team_def_sacks float, team_def_interceptions float,
  edge1_sacks float, edge1_tackles float, edge1_pass_defended float,
  edge2_sacks float, edge2_tackles float, edge2_pass_defended float,
  dt1_tackles float, dt1_sacks float, dt1_pass_defended float,
  dt2_tackles float, dt2_sacks float, dt2_pass_defended float,
  lb1_tackles float, lb1_sacks float, lb1_interceptions float, lb1_pass_defended float,
  lb2_tackles float, lb2_sacks float, lb2_interceptions float, lb2_pass_defended float,
  cb1_interceptions float, cb1_pass_defended float, cb1_tackles float,
  cb2_interceptions float, cb2_pass_defended float, cb2_tackles float,
  s1_tackles float, s1_interceptions float, s1_pass_defended float,
  k_fg_made float, k_fg_att float, k_fg_pct float,
  k_pat_made float, k_pat_att float,
  p_punt_attempts float, p_punt_yards float, p_punt_inside_20 float, p_punt_net_yards float,
  rs1_kr_att float, rs1_kr_yds float, rs1_pr_att float, rs1_pr_yds float,
  ol_sacks_allowed float,
  ol_qb_hits_allowed float,
  ol_rush_yards_per_carry float,
  ot1_snap_share float, ot1_games float,
  ot2_snap_share float, ot2_games float,
  og1_snap_share float, og1_games float,
  og2_snap_share float, og2_games float,
  c1_snap_share float,  c1_games float,
  ls_primary_snap_share float, ls_roster_churn int,
  unique (team, season)
);
